version: "3.7"

services:
  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888

  kafka:
    image: confluentinc/cp-kafka:5.2.1
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  mongo:
    image: bitnami/mongodb:latest
    hostname: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

  cassandra:
    image: bitnami/cassandra:latest
    hostname: cassandra
    container_name: cassandra
    ports:
      - 9042:9042

  cassandra-client:
    image: bitnami/cassandra:latest
    hostname: cassandra-client
    container_name: cassandra-client
    links:
      - cassandra
    depends_on:
      - cassandra
    volumes:
      - ./docker/cassandra:/cassandra
    command:
      - /bin/sh
      - -c
      - |
        cd /cassandra
        ./schema.sh